#!/bin/bash
#
# @file monitor
# ☆  Script talk to an Ardiuno via its USB connection
# @author Alister Lewis-Bowen <alister@different.com>
# @requires color <http://code.google.com/p/ansi-color/>
#
# This software is distributed under the the MIT License.
#
# Copyright (c) 2012 Alister Lewis-Bowen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Bootstrap
#
LIB=$( cd "$( dirname "$0" )" && pwd )/lib
source $LIB/core       # core vars and functions
source $LIB/connection # connection logic
source $LIB/jog        # jog mode

function _helpCmd {
    local helpText="$(color yellow)
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id convallis
quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia
interdum purus, suscipit venenatis enim vestibulum id. Nam cursus, tellus a
egestas consequat, turpis libero vestibulum nulla, sed gravida nibh mauris
non tellus.
$(color)
"
    echo "$helpText"
    exit 0;
}

function _helpLoop {
    local helpText="$(color yellow)
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id convallis
quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia
interdum purus, suscipit venenatis enim vestibulum id. Nam cursus, tellus a
egestas consequat, turpis libero vestibulum nulla, sed gravida nibh mauris
non tellus.
$(color)
"
    echo "$helpText"
}

case "$1" in
    '-h'|'--help'|'help')   _helpCmd;;
    '--new-device')         conRemoveDeviceStore;;
esac

# TODO: Migrate connection control into command loop
conOpen

while true; do

    [ "$MODE" == "$START_UP" ] && _helpLoop # offer some help on start up
    MODE=$RAW                               # default to raw mode

    echo -n "$(color yellow)[monitor] > $(color)"
    read input

    case "$input" in
        'help') _helpLoop;;
        'exit') conClose;;
        'jog')  jogMode;;
        'home') jogHome;;
        *)  # Process raw input
            conSend "$input"
            echo
            ;;
    esac
done;
