#!/bin/bash
#
# @file waypoints
# ☆  Waypoint manager for gcode_sender
# @author Alister Lewis-Bowen <alister@different.com>
# @requires color <http://code.google.com/p/ansi-color/>
#
# This software is distributed under the the MIT License.
#
# Copyright (c) 2012 Alister Lewis-Bowen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Waypoint store
#
WAYPOINT_STORE=~/.gcode_sender_waypoints

function wpRemoveStore {
    rm -f $WAYPOINT_STORE 2>/dev/null
}

function wpStore {
    local name=$1
    echo "$(color yellow)Setting waypoint, $1, for co-ods $XPOS, $YPOS, \
$ZPOS.$(color)"
    # TODO: record a wp to the store, e.g. name:X:Y:Z
}

function wpRemove {
    local name=$1
    echo "$(color yellow)Removing waypoint, $1$(color)"
    # TODO: remove a wp from the store
}

function wpStoreLimit {
    wpStore LIMIT
    echo "$(color yellow)Note: This waypoint is marked as the upper limit for \
each axis$(color)"
    # TODO: Add limit check to jog feature
}

function wpGoto {
    local name=$1
    # TODO: send wp co-ords to device
    echo "$(color yellow)Moving to waypoint, $1, at co-ods $XPOS, $YPOS, \
$ZPOS.$(color)"
    # TODO: send wp co-ords to device
}

function wpList {
    # TODO: list wps
    echo 'list of wps'
}
