#!/bin/bash
#
# @file waypoints
# ☆  Waypoint manager for gcode_sender
# @author Alister Lewis-Bowen <alister@different.com>
# @requires color <http://code.google.com/p/ansi-color/>
#
# This software is distributed under the the MIT License.
#
# Copyright (c) 2012 Alister Lewis-Bowen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# Waypoint store
#
WAYPOINT_STORE=~/.gcode_sender_waypoints

function wpExists {
    local matches=$(grep "^$1:" $WAYPOINT_STORE | wc -l)
    [ "$matches" -gt '0' ] && return 0
    return 1
}

function wpClearStore {
    rm -f $WAYPOINT_STORE 2>/dev/null
    touch $WAYPOINT_STORE
}

function wpStore {
    local name=$1
    wpExists $name
    if [ $? -eq 1 ]; then
        echo "$name:$XPOS:$YPOS:$ZPOS" >> $WAYPOINT_STORE
        echo "Waypoint has been added"
    else
        echo "This waypoint already exists:"
        wpList
    fi
}

function wpRemove {
    local name=$1
    wpExists $name
    if [ $? -eq 0 ]; then
        sed -i"*.bak" "/^$name:/d" $WAYPOINT_STORE &&
            echo "Waypoint has been removed"
    else
        echo "Unable to find waypoint '$name':"
        wpList
    fi
}

function wpStoreLimit {
    wpStore LIMIT
    echo "Note: This waypoint is marked as the upper limit for each axis."
    XMAX=$XPOS; YMAX=$YPOS; ZMAX=$ZPOS
}

function wpGoto {
    local name=$1
    wpExists $name
    if [ $? -eq 0 ]; then
        split ':' $(grep $name $WAYPOINT_STORE) wp
        XPOS=${wp[1]}; YPOS=${wp[2]}; ZPOS=${wp[3]}
        echo "Moving to waypoint '$name'"
        jogSend
    else
        echo "Unable to find waypoint '$name':"
        wpList
    fi
}

function wpList {
    local current="$(color blue)►$(color)"
    local wp=''
    local state=' '
    while read line; do
        split ':' $line wp
        state=' '
        [ $XPOS -eq ${wp[1]} ] &&
        [ $YPOS -eq ${wp[2]} ] &&
        [ $ZPOS -eq ${wp[3]} ] && state=$current
        printf "%1s $(color bd)%-10s$(color) %04d, %04d, %04d\n" \
           "$state" ${wp[0]} ${wp[1]} ${wp[2]} ${wp[3]}
    done < $WAYPOINT_STORE
}
